#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Synthetic DAS Soil Classification - A1

Goal
- Generate a multiclass synthetic DAS dataset (one soil per sample).
- Extract simple physics-inspired + signal features.
- Train robust baseline ML models.
- Save ALL artifacts for GitHub with:
    ./saida_synthetic_das_A1/run_YYYYMMDD_HHMM/
    ./saida_synthetic_das_A1/latest/

No TensorFlow/Keras. Pure numpy/pandas/scikit-learn/matplotlib/h5py.

Run (Windows / Thonny)
- Activate your venv
- python Synthetic_das_soil_A1.py --help
- python Synthetic_das_soil_A1.py --samples-per-class 300

Author: generated by ChatGPT
"""

import argparse
import json
import math
import os
import shutil
from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List, Tuple

import numpy as np

def safe_filename(s):
    s = str(s)
    s = s.replace("/", "-")
    s = s.replace("\\", "-")
    s = s.replace(":", "-")
    s = s.replace("*", "-")
    s = s.replace("?", "-")
    s = s.replace('"', "-")
    s = s.replace("<", "-")
    s = s.replace(">", "-")
    s = s.replace("|", "-")
    return s


# Optional deps: keep imports local so the script prints a clear message.


# -----------------------------
# Config
# -----------------------------

SOIL_CLASSES_PTBR: List[str] = [
    "Turfa/Lama",
    "Loam",
    "Argila mole",
    "Argila firme/Limo",
    "Silt Arenoso",
    "Areia solta",
    "Areia densa/Seixo",
    "Areia/Gravel",
    "Rocha macia",
    "Xisto/Calcario",
    "Basalto/Granito",
]

# Representative Vp (m/s) per class (simple, adjustable)
VEL_MAP_VP: Dict[str, float] = {
    "Turfa/Lama": 100.0,
    "Loam": 250.0,
    "Argila mole": 400.0,
    "Argila firme/Limo": 600.0,
    "Silt Arenoso": 900.0,
    "Areia solta": 1300.0,
    "Areia densa/Seixo": 1800.0,
    "Areia/Gravel": 2200.0,
    "Rocha macia": 2800.0,
    "Xisto/Calcario": 4000.0,
    "Basalto/Granito": 5500.0,
}

VEL_SIGMA_VP = {
    "Turfa/Lama": 30.0,
    "Loam": 40.0,
    "Argila mole": 60.0,
    "Argila firme/Limo": 80.0,
    "Silt Arenoso": 120.0,
    "Areia solta": 150.0,
    "Areia densa/Seixo": 180.0,
    "Areia/Gravel": 220.0,
    "Rocha macia": 300.0,
    "Xisto/Calcario": 400.0,
    "Basalto/Granito": 600.0,
}

@dataclass
class SimParams:
    n_channels: int
    z_max_m: float
    dt_fast_s: float
    n_fast: int
    pulse_width_s: float
    noise_sigma: float
    amp0: float
    atten_alpha: float
    jitter_s: float
    band_hz: float
    seed: int


# -----------------------------
# Utilities
# -----------------------------

def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def timestamp_run_name() -> str:
    return "run_" + datetime.now().strftime("%Y%m%d_%H%M")


def hard_reset_dir(path: str) -> None:
    if os.path.isdir(path):
        shutil.rmtree(path)
    os.makedirs(path, exist_ok=True)


def sync_latest(run_dir: str, latest_dir: str) -> None:
    """Overwrite latest/ with the contents of run_dir."""
    hard_reset_dir(latest_dir)
    # copytree requires dest not to exist; we already created it.
    for name in os.listdir(run_dir):
        src = os.path.join(run_dir, name)
        dst = os.path.join(latest_dir, name)
        if os.path.isdir(src):
            shutil.copytree(src, dst)
        else:
            shutil.copy2(src, dst)


def safe_imports():
    try:
        import pandas as pd  # noqa: F401
        import h5py  # noqa: F401
        import matplotlib.pyplot as plt  # noqa: F401
        from sklearn.model_selection import train_test_split  # noqa: F401
        from sklearn.preprocessing import StandardScaler  # noqa: F401
        from sklearn.pipeline import Pipeline  # noqa: F401
        from sklearn.linear_model import LogisticRegression  # noqa: F401
        from sklearn.ensemble import HistGradientBoostingClassifier  # noqa: F401
        from sklearn.metrics import (
            accuracy_score,
            f1_score,
            classification_report,
            confusion_matrix,
        )  # noqa: F401
    except Exception as e:
        raise RuntimeError(
            "Missing dependencies. Install with: pip install -r requirements.txt\n"
            f"Original error: {e}"
        )


def set_global_seed(seed: int) -> np.random.Generator:
    return np.random.default_rng(int(seed))


def gaussian_pulse(t: np.ndarray, t0: float, width: float, f0: float) -> np.ndarray:
    """Gaussian-modulated cosine pulse."""
    # width is standard deviation (s)
    x = (t - t0) / max(width, 1e-9)
    env = np.exp(-0.5 * x * x)
    return env * np.cos(2.0 * math.pi * f0 * (t - t0))


def moving_rms(x: np.ndarray, win: int) -> np.ndarray:
    """Envelope proxy: sqrt(moving average of x^2)."""
    win = int(max(3, win))
    if win % 2 == 0:
        win += 1
    kernel = np.ones(win, dtype=np.float32) / float(win)
    x2 = (x.astype(np.float32) ** 2)
    y = np.convolve(x2, kernel, mode="same")
    return np.sqrt(np.maximum(y, 0.0))


def spectral_features(x: np.ndarray, dt: float) -> Tuple[float, float, float, float]:
    """Return (centroid_hz, bandwidth_hz, rolloff_hz, peak_hz) from rFFT."""
    x = x.astype(np.float64)
    n = x.size
    if n < 8:
        return 0.0, 0.0, 0.0, 0.0

    # remove DC
    x = x - float(np.mean(x))
    X = np.fft.rfft(x)
    P = (np.abs(X) ** 2)
    freqs = np.fft.rfftfreq(n, d=dt)

    psum = float(np.sum(P))
    if psum <= 1e-12:
        return 0.0, 0.0, 0.0, 0.0

    centroid = float(np.sum(freqs * P) / psum)
    bandwidth = float(np.sqrt(np.sum(((freqs - centroid) ** 2) * P) / psum))

    # rolloff: frequency below which 85% of energy lies
    cumsum = np.cumsum(P)
    thr = 0.85 * cumsum[-1]
    idx = int(np.searchsorted(cumsum, thr))
    idx = int(np.clip(idx, 0, freqs.size - 1))
    rolloff = float(freqs[idx])

    peak_idx = int(np.argmax(P))
    peak_hz = float(freqs[peak_idx])

    return centroid, bandwidth, rolloff, peak_hz


def simple_kurtosis(x: np.ndarray) -> float:
    x = x.astype(np.float64)
    mu = float(np.mean(x))
    v = float(np.mean((x - mu) ** 2))
    if v <= 1e-12:
        return 0.0
    m4 = float(np.mean((x - mu) ** 4))
    return m4 / (v * v)


def simple_skewness(x: np.ndarray) -> float:
    x = x.astype(np.float64)
    mu = float(np.mean(x))
    s = float(np.std(x))
    if s <= 1e-12:
        return 0.0
    m3 = float(np.mean((x - mu) ** 3))
    return m3 / (s ** 3)


# -----------------------------
# Simulation
# -----------------------------

def simulate_one_sample(soil_name: str, base_seed: int, sample_idx: int, params: SimParams) -> Tuple[np.ndarray, Dict[str, float]]:
    """Return (strain[K, Nt], metadata)."""
    rng = np.random.default_rng(int(base_seed) + 100000 * int(sample_idx) + 17)

    vp_mu = float(VEL_MAP_VP[soil_name])
    vp_sigma = float(VEL_SIGMA_VP.get(soil_name, 0.1 * vp_mu))

    vp = float(rng.normal(vp_mu, vp_sigma))
    vp = float(np.clip(vp, 0.3 * vp_mu, 3.0 * vp_mu))


    # Depth axis
    K = int(params.n_channels)
    z = np.linspace(0.0, float(params.z_max_m), K, dtype=np.float32)

    # Fast-time axis
    dt = float(params.dt_fast_s)
    Nt = int(params.n_fast)
    t = (np.arange(Nt, dtype=np.float32) * dt)

    # Per-sample variability
    amp0 = float(params.amp0) * float(rng.uniform(0.7, 1.3))
    noise_sigma = float(params.noise_sigma) * float(rng.uniform(0.6, 1.6))
    alpha = float(params.atten_alpha) * float(rng.uniform(0.6, 1.4))
    jitter = float(params.jitter_s) * float(rng.uniform(0.5, 1.5))

    # Pulse bandwidth / center frequency
    f0 = float(params.band_hz) * float(rng.uniform(0.7, 1.3))
    width = float(params.pulse_width_s) * float(rng.uniform(0.7, 1.3))

    strain = np.zeros((K, Nt), dtype=np.float32)

    # Two-way travel time (simple) + depth-dependent attenuation
    # t_arr(z) in seconds
    t_arr = (2.0 * z.astype(np.float64)) / max(vp, 1.0)

    for k in range(K):
        t0 = float(t_arr[k]) + float(rng.normal(0.0, jitter))
        a = amp0 * math.exp(-alpha * float(z[k]))
        sig = gaussian_pulse(t, t0, width, f0).astype(np.float32)

        # Add a small later reflection (optional) for realism
        if rng.random() < 0.35:
            t1 = t0 + float(rng.uniform(0.02, 0.09))
            a1 = a * float(rng.uniform(0.15, 0.45))
            sig = sig + (a1 * gaussian_pulse(t, t1, width * 1.2, f0 * 0.8).astype(np.float32))

        # Noise
        sig = sig + rng.normal(0.0, noise_sigma, size=Nt).astype(np.float32)
        strain[k, :] = sig

    meta = {
        "vp": vp,
        "amp0": amp0,
        "noise_sigma": noise_sigma,
        "atten_alpha": alpha,
        "pulse_f0_hz": f0,
        "pulse_width_s": width,
    }
    return strain, meta


# -----------------------------
# Feature extraction
# -----------------------------

def estimate_vp_from_arrival(strain: np.ndarray, z: np.ndarray, dt: float) -> float:
    """Rough Vp estimate using picked arrival index vs depth.

    We pick the envelope peak index per channel, then fit t(z) = a*z + b.
    For a two-way model: t ~ 2*z/vp => vp ~ 2/a.

    This is intentionally simple/robust.
    """
    K, Nt = strain.shape
    if K < 4:
        return float("nan")

    # Use a smoothed envelope proxy to reduce noise.
    win = max(9, int(0.006 / dt))  # ~6 ms window
    picks = np.zeros(K, dtype=np.float64)

    for k in range(K):
        env = moving_rms(strain[k, :], win=win)
        # restrict search to avoid picking pure noise at the end
        search_end = int(max(16, 0.8 * Nt))
        idx = int(np.argmax(env[:search_end]))
        picks[k] = float(idx) * dt

    # Fit t = a*z + b
    zz = z.astype(np.float64)
    if np.allclose(zz, zz[0]):
        return float("nan")

    A = np.vstack([zz, np.ones_like(zz)]).T
    try:
        coeff, _, _, _ = np.linalg.lstsq(A, picks, rcond=None)
        a = float(coeff[0])
        if abs(a) <= 1e-12:
            return float("nan")
        vp_hat = 2.0 / a
        return float(vp_hat)
    except Exception:
        return float("nan")


def extract_features_one(strain: np.ndarray, z: np.ndarray, dt: float) -> Dict[str, float]:
    K, Nt = strain.shape

    # Aggregate trace: mean over channels (common for stable spectral features)
    trace_mean = np.mean(strain, axis=0).astype(np.float32)

    # Basic energy stats
    rms_all = float(np.sqrt(np.mean(strain.astype(np.float64) ** 2)))
    rms_trace = float(np.sqrt(np.mean(trace_mean.astype(np.float64) ** 2)))
    abs_mean = float(np.mean(np.abs(trace_mean)))
    abs_max = float(np.max(np.abs(trace_mean)))

    # Envelope stats on mean trace
    win = max(9, int(0.006 / dt))
    env = moving_rms(trace_mean, win=win)
    env_mean = float(np.mean(env))
    env_max = float(np.max(env))
    env_p95 = float(np.percentile(env, 95))

    # Spectral
    centroid, bw, rolloff, peak_hz = spectral_features(trace_mean, dt=dt)

    # Shape
    kurt = float(simple_kurtosis(trace_mean))
    skew = float(simple_skewness(trace_mean))

    # Physics-inspired
    vp_hat = float(estimate_vp_from_arrival(strain, z=z, dt=dt))

    # SNR proxy: envelope peak / envelope median
    env_med = float(np.median(env))
    snr_proxy = float(env_max / max(env_med, 1e-9))

    return {
        "rms_all": rms_all,
        "rms_trace": rms_trace,
        "abs_mean": abs_mean,
        "abs_max": abs_max,
        "env_mean": env_mean,
        "env_max": env_max,
        "env_p95": env_p95,
        "snr_proxy": snr_proxy,
        "spec_centroid_hz": float(centroid),
        "spec_bandwidth_hz": float(bw),
        "spec_rolloff_hz": float(rolloff),
        "spec_peak_hz": float(peak_hz),
        "kurtosis": kurt,
        "skewness": skew,
        "vp_hat": vp_hat,
    }


# -----------------------------
# Plotting
# -----------------------------

def plot_class_hist(labels: np.ndarray, class_names: List[str], out_png: str) -> None:
    import matplotlib.pyplot as plt

    counts = np.bincount(labels, minlength=len(class_names))
    x = np.arange(len(class_names))

    plt.figure(figsize=(12, 4))
    plt.bar(x, counts)
    plt.xticks(x, class_names, rotation=35, ha="right")
    plt.ylabel("Contagem")
    plt.title("Composicao do dataset por classe")
    plt.tight_layout()
    plt.savefig(out_png, dpi=160)
    plt.close()


def plot_confusion(cm: np.ndarray, class_names: List[str], out_png: str, title: str) -> None:
    import matplotlib.pyplot as plt

    plt.figure(figsize=(8, 7))
    plt.imshow(cm, aspect="auto")
    plt.title(title)
    plt.colorbar()
    ticks = np.arange(len(class_names))
    plt.xticks(ticks, class_names, rotation=45, ha="right")
    plt.yticks(ticks, class_names)

    # annotate
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(j, i, str(cm[i, j]), ha="center", va="center", fontsize=8)

    plt.xlabel("Predito")
    plt.ylabel("Verdade")
    plt.tight_layout()
    plt.savefig(out_png, dpi=170)
    plt.close()


def plot_examples(per_class_example: Dict[str, Dict], out_dir: str) -> None:
    import matplotlib.pyplot as plt

    ensure_dir(out_dir)

    for soil, ex in per_class_example.items():
        soil_fn = safe_filename(soil)
        strain = ex["strain"]
        z = ex["z"]
        dt = float(ex["dt"])
        vp = float(ex["vp"])

        K, Nt = strain.shape
        t = np.arange(Nt, dtype=np.float32) * dt

        # 1) raw signature: mean trace
        mean_trace = np.mean(strain, axis=0)
        plt.figure(figsize=(10, 3))
        plt.plot(t, mean_trace)
        plt.title(f"Raw signature (mean trace) - {soil} (Vp={vp:.0f} m/s)")
        plt.xlabel("Tempo (s)")
        plt.ylabel("Strain (a.u.)")
        plt.tight_layout()
        plt.savefig(os.path.join(out_dir, f"{soil_fn}_raw_signature.png"), dpi=160)
        plt.close()

        # 2) heatmap strain (subset channels)
        step = max(1, K // 64)
        sub = strain[::step, :]
        plt.figure(figsize=(10, 4))
        plt.imshow(sub, aspect="auto", extent=[t[0], t[-1], float(z[-1]), float(z[0])])
        plt.title(f"Heatmap strain (subset channels) - {soil}")
        plt.xlabel("Tempo (s)")
        plt.ylabel("Profundidade z (m)")
        plt.colorbar(label="strain")
        plt.tight_layout()
        plt.savefig(os.path.join(out_dir, f"{soil_fn}_heatmap_strain.png"), dpi=160)
        plt.close()

        # 3) arrival fast-time vs depth (picked via envelope)
        win = max(9, int(0.006 / dt))
        picks = []
        for k in range(K):
            env = moving_rms(strain[k, :], win=win)
            search_end = int(max(16, 0.8 * Nt))
            idx = int(np.argmax(env[:search_end]))
            picks.append(idx)
        picks = np.array(picks, dtype=int)

        plt.figure(figsize=(6, 4))
        plt.scatter(picks, z, s=6, alpha=0.7)
        plt.gca().invert_yaxis()
        plt.title(f"Arrival index (fast-time) vs depth - {soil}")
        plt.xlabel("Indice de amostra (fast-time)")
        plt.ylabel("Profundidade z (m)")
        plt.tight_layout()
        plt.savefig(os.path.join(out_dir, f"{soil_fn}_arrival_fasttime_vs_depth.png"), dpi=160)
        plt.close()

        # 4) envelope peaks distribution (mean trace)
        env_mean = moving_rms(mean_trace.astype(np.float32), win=win)
        plt.figure(figsize=(10, 3))
        plt.plot(t, env_mean)
        plt.title(f"Envelope proxy (moving RMS) - {soil}")
        plt.xlabel("Tempo (s)")
        plt.ylabel("Envelope (a.u.)")
        plt.tight_layout()
        plt.savefig(os.path.join(out_dir, f"{soil_fn}_envelope.png"), dpi=160)
        plt.close()


# -----------------------------
# Main pipeline
# -----------------------------

def build_dataset(
    class_names: List[str],
    samples_per_class: int,
    base_seed: int,
    sim_params: SimParams,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, List[Dict[str, float]]]:
    """Return X, y, z, meta_list."""
    rng = np.random.default_rng(int(base_seed))

    n_classes = len(class_names)
    n_total = int(samples_per_class) * n_classes

    K = int(sim_params.n_channels)
    Nt = int(sim_params.n_fast)
    z = np.linspace(0.0, float(sim_params.z_max_m), K, dtype=np.float32)

    X = np.zeros((n_total, K, Nt), dtype=np.float32)
    y = np.zeros((n_total,), dtype=np.int32)
    meta_list: List[Dict[str, float]] = []

    idx = 0
    for ci, soil in enumerate(class_names):
        for si in range(int(samples_per_class)):
            # vary per sample with deterministic seed based on class+index
            strain, meta = simulate_one_sample(
                soil_name=soil,
                base_seed=int(base_seed) + 1000 * ci,
                sample_idx=si,
                params=sim_params,
            )
            X[idx, :, :] = strain
            y[idx] = int(ci)
            meta_list.append(meta)
            idx += 1

    # Shuffle samples
    perm = rng.permutation(n_total)
    X = X[perm]
    y = y[perm]
    meta_list = [meta_list[i] for i in perm]

    return X, y, z, meta_list


def save_h5(out_path: str, X: np.ndarray, y: np.ndarray, z: np.ndarray, class_names: List[str], dt: float, meta_list: List[Dict[str, float]]) -> None:
    import h5py

    # Prepare meta arrays
    vp_arr = np.array([m.get("vp", np.nan) for m in meta_list], dtype=np.float32)
    amp0_arr = np.array([m.get("amp0", np.nan) for m in meta_list], dtype=np.float32)
    noise_arr = np.array([m.get("noise_sigma", np.nan) for m in meta_list], dtype=np.float32)
    atten_arr = np.array([m.get("atten_alpha", np.nan) for m in meta_list], dtype=np.float32)
    f0_arr = np.array([m.get("pulse_f0_hz", np.nan) for m in meta_list], dtype=np.float32)
    w_arr = np.array([m.get("pulse_width_s", np.nan) for m in meta_list], dtype=np.float32)

    with h5py.File(out_path, "w") as f:
        f.create_dataset("X", data=X, compression="gzip", compression_opts=4)
        f.create_dataset("y", data=y)
        f.create_dataset("z", data=z)
        f.create_dataset("dt_fast_s", data=np.array([dt], dtype=np.float32))

        # class names as UTF-8 strings (future-proof for accents)
        dt_str = h5py.string_dtype(encoding="utf-8")
        f.create_dataset("class_names", data=np.array(class_names, dtype=dt_str))

        g = f.create_group("meta")
        g.create_dataset("vp", data=vp_arr)
        g.create_dataset("amp0", data=amp0_arr)
        g.create_dataset("noise_sigma", data=noise_arr)
        g.create_dataset("atten_alpha", data=atten_arr)
        g.create_dataset("pulse_f0_hz", data=f0_arr)
        g.create_dataset("pulse_width_s", data=w_arr)


def train_and_evaluate(
    features_csv: str,
    metrics_json: str,
    cm_png: str,
    class_names: List[str],
    seed: int,
    drop_cols: List[str] = None,
    model_out_path: str = None,
) -> None:
    import pandas as pd
    from sklearn.model_selection import train_test_split
    from sklearn.preprocessing import StandardScaler
    from sklearn.pipeline import Pipeline
    from sklearn.linear_model import LogisticRegression
    from sklearn.ensemble import HistGradientBoostingClassifier
    from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

    df = pd.read_csv(features_csv)

    # Optional: drop columns that can leak ground-truth or are not intended as inputs.
    if drop_cols:
        for c in drop_cols:
            if c in df.columns:
                df = df.drop(columns=[c])

    y = df["label_id"].values.astype(int)
    X = df.drop(columns=["label_id", "label_name"]).values

    # Robust split: stratified split needs at least 2 samples per class in the test set.
    n_samples = int(X.shape[0])
    n_classes = int(len(class_names))
    desired_test = max(1, int(round(0.20 * n_samples)))
    min_test = 2 * n_classes
    test_n = max(desired_test, min_test)
    if test_n >= n_samples:
        # Too small to split properly; skip ML gracefully.
        payload = {
            "best_model": None,
            "results": {},
            "seed": int(seed),
            "n_classes": n_classes,
            "n_features": int(X.shape[1]),
            "n_samples": n_samples,
            "warning": "Dataset too small for stratified train/test split; ML step skipped.",
        }
        with open(metrics_json, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)
        return

    test_size = float(test_n) / float(n_samples)

    Xtr, Xte, ytr, yte = train_test_split(
        X,
        y,
        test_size=test_size,
        random_state=int(seed),
        stratify=y,
    )

    models = {}

    # Model 1: Logistic Regression (scaled)
    models["logreg"] = Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            (
                "clf",
                LogisticRegression(
                    max_iter=2000,
                    solver="lbfgs",
                    random_state=int(seed),
                ),
            ),
        ]
    )

    # Model 2: HistGradientBoosting (no scaling needed)
    models["hgb"] = HistGradientBoostingClassifier(
        random_state=int(seed),
        max_depth=6,
        learning_rate=0.08,
        max_iter=250,
    )

    results = {}
    best_name = None
    best_score = -1.0

    best_model = None
    for name, model in models.items():
        model.fit(Xtr, ytr)
        pred = model.predict(Xte)
        acc = float(accuracy_score(yte, pred))
        f1m = float(f1_score(yte, pred, average="macro"))
        rep = classification_report(yte, pred, target_names=class_names, output_dict=True, zero_division=0)
        cm = confusion_matrix(yte, pred, labels=list(range(len(class_names))))

        results[name] = {
            "accuracy": acc,
            "f1_macro": f1m,
            "classification_report": rep,
            "confusion_matrix": cm.tolist(),
        }

        if f1m > best_score:
            best_score = f1m
            best_name = name
            best_model = model

    assert best_name is not None

    # Save confusion plot for best
    cm_best = np.array(results[best_name]["confusion_matrix"], dtype=int)
    plot_confusion(cm_best, class_names, cm_png, title=f"Confusion Matrix (best={best_name})")

    payload = {
        "best_model": best_name,
        "results": results,
        "seed": int(seed),
        "n_classes": int(len(class_names)),
        "n_features": int(X.shape[1]),
        "n_samples": int(X.shape[0]),
    }

    with open(metrics_json, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)

    # Optional: persist best model for reproducibility.
    if model_out_path and best_model is not None:
        try:
            import joblib

            joblib.dump(best_model, model_out_path)
        except Exception as e:
            # Do not fail the run if joblib is missing.
            print(f"[WARN] Could not save model to {model_out_path}: {e}")


def main() -> None:
    safe_imports()

    import pandas as pd

    ap = argparse.ArgumentParser(description="Synthetic DAS Soil Classification - A1")
    ap.add_argument("--outdir", default="./saida_synthetic_das_A1", help="Base output directory")
    ap.add_argument("--samples-per-class", type=int, default=250, help="Samples per class")
    ap.add_argument("--seed", type=int, default=42, help="Random seed")
    ap.add_argument("--n-channels", type=int, default=128, help="Number of DAS channels")
    ap.add_argument("--z-max", type=float, default=120.0, help="Max depth (m)")
    ap.add_argument("--dt-fast", type=float, default=0.0005, help="Fast-time sampling (s)")
    ap.add_argument("--n-fast", type=int, default=2048, help="Fast-time samples")
    ap.add_argument("--pulse-width", type=float, default=0.004, help="Pulse width (s)")
    ap.add_argument("--band-hz", type=float, default=55.0, help="Pulse center frequency (Hz)")
    ap.add_argument("--noise", type=float, default=0.020, help="Base noise sigma")
    ap.add_argument("--amp", type=float, default=1.00, help="Base amplitude")
    ap.add_argument("--atten", type=float, default=0.012, help="Depth attenuation alpha")
    ap.add_argument("--jitter", type=float, default=0.0012, help="Arrival jitter (s)")
    ap.add_argument("--max-classes", type=int, default=len(SOIL_CLASSES_PTBR), help="Use only first N classes")
    # Output control
    ap.add_argument("--latest-only", action="store_true", help="Write outputs directly into outdir/latest (no timestamped run folder)")
    ap.add_argument("--no-sync-latest", action="store_true", help="Do not copy/sync run outputs into outdir/latest")
    ap.add_argument("--skip-examples", action="store_true", help="Do not generate per-class example plots")
    ap.add_argument("--skip-ml", action="store_true", help="Skip training/evaluation (generate dataset+features only)")
    ap.add_argument("--make-h5", action="store_true", help="Also save full dataset to HDF5 (can be large)")
    ap.add_argument(
        "--drop-cols",
        type=str,
        default="vp_true,vs_true,rho_true,alpha_att_true,snr",
        help="Comma-separated columns to drop before ML (avoid leakage). Use empty string to drop nothing.",
    )
    ap.add_argument("--save-model", action="store_true", help="Save the best trained model as artifacts/model_best.joblib")
    args = ap.parse_args()

    class_names = SOIL_CLASSES_PTBR[: int(args.max_classes)]

    base_out = os.path.abspath(args.outdir)
    ensure_dir(base_out)

    latest_dir = os.path.join(base_out, "latest")
    run_name = timestamp_run_name()
    run_dir = latest_dir if args.latest_only else os.path.join(base_out, run_name)

    ensure_dir(run_dir)
    if not args.skip_examples:
        ensure_dir(os.path.join(run_dir, "examples"))

    sim_params = SimParams(
        n_channels=int(args.n_channels),
        z_max_m=float(args.z_max),
        dt_fast_s=float(args.dt_fast),
        n_fast=int(args.n_fast),
        pulse_width_s=float(args.pulse_width),
        noise_sigma=float(args.noise),
        amp0=float(args.amp),
        atten_alpha=float(args.atten),
        jitter_s=float(args.jitter),
        band_hz=float(args.band_hz),
        seed=int(args.seed),
    )

    print("[INFO] Building dataset A1...")
    X, y, z, meta_list = build_dataset(
        class_names=class_names,
        samples_per_class=int(args.samples_per_class),
        base_seed=int(args.seed),
        sim_params=sim_params,
    )

    # Save class composition plot
    plot_class_hist(y, class_names, out_png=os.path.join(run_dir, "class_hist.png"))

    # Extract features
    print("[INFO] Extracting features...")
    feats_rows = []

    # Keep one example per class
    per_class_example: Dict[str, Dict] = {}

    for i in range(X.shape[0]):
        strain = X[i]
        label_id = int(y[i])
        label_name = class_names[label_id]

        f = extract_features_one(strain, z=z, dt=float(sim_params.dt_fast_s))
        row = {"label_id": label_id, "label_name": label_name}
        row.update(f)

        # store selected sim meta too
        row["vp_true"] = float(meta_list[i].get("vp", np.nan))
        row["noise_sigma"] = float(meta_list[i].get("noise_sigma", np.nan))
        row["atten_alpha"] = float(meta_list[i].get("atten_alpha", np.nan))
        row["pulse_f0_hz"] = float(meta_list[i].get("pulse_f0_hz", np.nan))
        row["pulse_width_s"] = float(meta_list[i].get("pulse_width_s", np.nan))
        row["amp0"] = float(meta_list[i].get("amp0", np.nan))

        feats_rows.append(row)

        if label_name not in per_class_example:
            per_class_example[label_name] = {
                "strain": strain.copy(),
                "z": z.copy(),
                "dt": float(sim_params.dt_fast_s),
                "vp": float(meta_list[i].get("vp", np.nan)),
            }

    df_feat = pd.DataFrame(feats_rows)

    # Save features
    features_csv = os.path.join(run_dir, "features.csv")
    df_feat.to_csv(features_csv, index=False)

    # Optional: save full dataset to HDF5 (can be large)
    if args.make_h5:
        h5_path = os.path.join(run_dir, "dataset_A1.h5")
        print("[INFO] Saving HDF5 dataset...", h5_path)
        save_h5(h5_path, X=X, y=y, z=z, class_names=class_names, dt=float(sim_params.dt_fast_s), meta_list=meta_list)
    else:
        print("[INFO] Skipping HDF5 dataset (--make-h5 not set)")

    # Examples
    if not args.skip_examples:
        print("[INFO] Saving example plots...")
        examples_dir = os.path.join(run_dir, "examples")
        ensure_dir(examples_dir)
        plot_examples(per_class_example, out_dir=examples_dir)
        # Quick sanity check: list at least one file
        try:
            n_png = len([p for p in os.listdir(examples_dir) if p.lower().endswith('.png')])
            print(f"[INFO] Example plots written: {n_png} PNG(s)")
        except Exception:
            pass
    else:
        print("[INFO] Skipping example plots (--skip-examples)")

    # Train and evaluate
    metrics_json = os.path.join(run_dir, "metrics.json")
    cm_png = os.path.join(run_dir, "confusion_matrix.png")
    model_out_path = os.path.join(run_dir, "model_best.joblib") if args.save_model else None
    drop_cols = [c.strip() for c in str(args.drop_cols).split(",") if c.strip()] if args.drop_cols is not None else []

    if args.skip_ml:
        print("[INFO] Skipping ML training/evaluation (--skip-ml)")
    else:
        print("[INFO] Training ML baselines...")
        train_and_evaluate(
            features_csv=features_csv,
            metrics_json=metrics_json,
            cm_png=cm_png,
            class_names=class_names,
            seed=int(args.seed),
            drop_cols=drop_cols,
            model_out_path=model_out_path,
        )

    # Save a small run summary
    artifacts = {
        "features_csv": "features.csv",
        "class_hist": "class_hist.png",
    }
    if args.make_h5:
        artifacts["dataset_h5"] = "dataset_A1.h5"
    if not args.skip_examples:
        artifacts["examples_dir"] = "examples/"
    if not args.skip_ml:
        artifacts["metrics_json"] = "metrics.json"
        artifacts["confusion_matrix"] = "confusion_matrix.png"
        if args.save_model:
            artifacts["model_joblib"] = "model_best.joblib"

    summary = {
        "run_name": run_name,
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "base_outdir": base_out,
        "n_samples": int(X.shape[0]),
        "samples_per_class": int(args.samples_per_class),
        "n_classes": int(len(class_names)),
        "class_names": class_names,
        "shape_X": [int(X.shape[0]), int(X.shape[1]), int(X.shape[2])],
        "dt_fast_s": float(sim_params.dt_fast_s),
        "z_max_m": float(sim_params.z_max_m),
        "seed": int(args.seed),
        "artifacts": artifacts,
    }
    with open(os.path.join(run_dir, "summary.json"), "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    # Sync latest/ (convenience folder)
    if args.latest_only:
        print("[INFO] latest-only mode: outputs are already in latest/")
    elif args.no_sync_latest:
        print("[INFO] Skipping latest/ sync (--no-sync-latest)")
    else:
        print("[INFO] Syncing latest/ ...")
        sync_latest(run_dir, latest_dir)

    print("\n[OK] Pipeline A1 executed.")
    print("Run dir:", run_dir)
    print("Latest dir:", latest_dir)


if __name__ == "__main__":
    main()




